# Generated by Django 2.2.6 on 2020-01-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('publishdate', models.DateField()),
                ('icon', models.ImageField(upload_to=None)),
                ('infoLink', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
