# Generated by Django 2.1.7 on 2019-03-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Book'},
        ),
    ]
