# Generated by Django 2.2.6 on 2020-01-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
