# Generated by Django 2.2.6 on 2020-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApi', '0002_auto_20200103_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
