# Generated by Django 2.1.7 on 2019-03-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApi', '0002_auto_20190320_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'book'},
        ),
    ]
