# Generated by Django 2.2.6 on 2020-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApi', '0003_auto_20200103_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='infoLink',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
